name: Deploy Infrastructure

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'iac-arm/rg-scope/**'
on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  TEMPLATE_FILE: iac-arm/rg-scope/main.json
  PARAMETER_FILE: iac-arm/rg-scope/main.parameters.json
  OBJ_ID: ${{ secrets.OBJ_ID }}

jobs:
  deploy-infra:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate ARM Template
        run: |
          az deployment group validate \
            --resource-group $RESOURCE_GROUP \
            --template-file $TEMPLATE_FILE \
            --parameters @$PARAMETER_FILE \
            --parameters githubSpObjectId=${{ secrets.OBJ_ID }}

      - name: Deploy ARM Template
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file $TEMPLATE_FILE \
            --parameters @$PARAMETER_FILE \
            --parameters githubSpObjectId=${{ secrets.OBJ_ID }} \
            --name infra-${{ github.run_number }} 
